# "No Response"
# https://github.com/probot/no-response

# Allowed number of days of inactivity
daysUntilClose: 21

# Label requiring a response
responseRequiredLabel: more-info-needed

# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
   This issue has been automatically closed due to a lack of response.
   If your problem persists please open a new issue including any additional detail
   requested from this issue.

